If:
  PathMatch: .*\.c
Diagnostics:
  UnusedIncludes: None
CompileFlags:
  Add: [-xc, -Wall, -Wextra]
---
If:
  PathMatch: .*\.h
CompileFlags:                     # Tweak the parse settings
  Add: [-xc, -Wall]
